text_win = "Sie haben GEWONNEN Sir, großer Reichtum wird Ihnen zu Teil."
text_lose = f"Sie haben verloren Sir, die Bank wird Ihren Reichtum leider einbehalten müssen. Wir hatten einfach die besseren Karten.\n"
text_switchAss = "Das Ass können wir jedoch mit der Wertigkeit 1 betrachten."
text_showCards = "Hier sind Ihre Karten"
banner = "##############################################\n"
text_moreCards = "Möchten Sie eine weitere Karte ziehen Sir?\n"
text_draw = "Gleichstand Sir, möchten Sie noch eine Runde spielen?"